#!/bin/bash

STANDARD="PSR12"
BIN="./vendor/bin"

# Check whether PHP_CodeSniffer can be found
if [ ! -f "$BIN/phpcs" ]
then
    echo
    echo "[PRE-COMMIT] PHP_CodeSniffer not found – is it installed? 'composer require --dev squizlabs/php_codesniffer'"
    echo
    exit 1
fi

# Run the sniffer
echo
echo "[PRE-COMMIT] Running PHP_CodeSniffer using the $STANDARD standard"
echo
# Retrieve staged files
FILES=$(git diff --cached --name-only --diff-filter=ACMR HEAD)
# PHPCS command
PHPCS=("$BIN/phpcs" "--standard=$STANDARD" "--filter=gitstaged" "--encoding=utf-8" "-p" ".")
"${PHPCS[@]}"

if [ $? != 0 ]
then
    echo "[PRE-COMMIT] Please fix all of the violations or commit with the --no-verify option"
    echo
    exit 1
else
    echo "[PRE-COMMIT] No violations detected"
    echo
    exit 0
fi
